# Basic setup
FROM node:18-alpine AS build
WORKDIR /app
COPY . /app
COPY package*.json ./

# Install dependencies and build the app
RUN npm install
COPY . .
RUN npm run build

# Run using nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Start Nginx server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]