import os
from enum import Enum

import dotenv

dotenv.load_dotenv(override=True)


GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
GOOGLE_PROJECT_ID = os.getenv("GOOGLE_PROJECT_ID")
GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT_CREDENTIALS_B64 = os.getenv(
    "GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT_CREDENTIALS"
)
GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT_EMAIL = os.getenv(
    "GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT_EMAIL"
)
ENVIRONMENT = os.getenv("ENVIRONMENT")


class Environment(Enum):
    PRODUCTION = "PRODUCTION"
    DEVELOPMENT = "DEVELOPMENT"
    LOCAL = "LOCAL"
