name: Auto Deploy to Google Cloud

on:
  push:
    branches:
      - feature-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      IMAGE_NAME: europe-west3-docker.pkg.dev/thf-climate-cloud/thf-climate/thf-climate

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > ${HOME}/gcloud-service-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Activate Service Account
        run: |
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud config set account $(gcloud config get-value core/account)

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Docker Login using Access Token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo $ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin https://europe-west3-docker.pkg.dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker buildx build --platform linux/amd64 \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        working-directory: ./backend
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        working-directory: ./backend
        run: |
          gcloud run deploy thf-climate-run \
            --image=$IMAGE_NAME:latest \
            --port=8000 \
            --region=europe-west3 \
            --allow-unauthenticated \
            --platform=managed \
            --min-instances=1 \
            --max-instances=5
