name: Auto Deploy to Google Cloud

on:
  push:
    branches:
      - feature-deploy

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: europe-west3-docker.pkg.dev/thf-climate-cloud/thf-climate/thf-climate

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Inspect Docker Configuration
        run: cat /home/runner/.docker/config.json

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker buildx build --platform linux/amd64 \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        working-directory: ./backend
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        working-directory: ./backend
        run: |
          gcloud run deploy thf-climate-run \
            --image=$IMAGE_NAME:latest \
            --port=8000 \
            --region=europe-west3 \
            --allow-unauthenticated \
            --platform=managed \
            --min-instances=1 \
            --max-instances=5
